"""empty message

Revision ID: 06e49ddcfeeb
Revises: 48115b87dd01
Create Date: 2020-06-21 15:48:14.053587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e49ddcfeeb'
down_revision = '48115b87dd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_item',
    sa.Column('venu_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venu_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venu_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_item')
    # ### end Alembic commands ###
